### ISSUE TITLE
Does not work with latest slate version slate@0.43.3

### ISSUE THREAD

**Issue by Yevs** [jasonphillips/slate-deep-table#7]
Slate had introduced breaking changes and slate-deep-table is no more compatible with latest slate.

**Comment by jasonphillips** [comment]
Closed by #8 - check the [changelog](https://github.com/jasonphillips/slate-deep-table/blob/master/CHANGELOG.md) and updated [example](https://github.com/jasonphillips/slate-deep-table/blob/master/example/main.js) for some updates to syntax and breaking changes.
