### ISSUE TITLE
wrong new keyword

### ISSUE THREAD

**Issue by bebbi** [jasonphillips/slate-deep-table#9]
I'm not sure why there's a new keyword at [this line](https://github.com/bebbi/slate-deep-table/blob/5ee86b2fb2cca9ed6afbbc4f1708acdec609c745/lib/TablePosition.js#L14), classes are extended without it:
https://facebook.github.io/immutable-js/docs/#/Record
If you like I can submit a PR.

**Comment by jasonphillips** [comment]
Thanks, corrected in https://github.com/jasonphillips/slate-deep-table/commit/c219c6e51eb82977c8fd491e81469b20677c26eb
